apiVersion: v1
kind: Service
metadata:
  name: pythonapp-svc
  namespace: pythonapp
  labels:
    app: python-app
spec:
  selector:
    app: python-app
  type: NodePort  
  ports:
  - port: 5000
    targetPort: 5000
